const plugin = require("tailwindcss/plugin");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontSize: {
        xxs: ["10.5px", { lineHeight: "15px", letterSpacing: "0.2px" }],
      },
      colors: {
        "basic-text": "#1A1A19",
        "blue-50": "#E6EDFF",
        "blue-100": "#CCDAFF",
        "blue-200": "#98B1F8",
        "blue-250": "#7F9EF7",
        "blue-500": "#1246DA",
        "blue-700": "#1246DA",
        "blue-750": "#00207B",
        "blue-800": "#002692",
        "blue-dark": "#001A63",
        "blue-900": "#000E33",
        "blue-gray-300": "#9EABD6",
        "blue-gray-400": "#6F7FA8",
        "blue-gray-600": "#424D6B",
        "green-50": "#E0FAEB",
        "green-100": "#B5F7D6",
        "green-150": "#D6EC96",
        "green-200": "#7FE7B3",
        "green-400": "#31C069",
        "green-500": "#00B85C",
        "green-600": "#00974B",
        "gray-25": "#FAFAFA",
        "gray-50": "#F4F4F3",
        "gray-100": "#E9E9E8",
        "gray-200": "#CFCFCD",
        "gray-400": "#9B9B98",
        "gray-500": "#81817E",
        "gray-600": "#686864",
        "light-purple": "#D2DAFF",
        "gray-900": "#1A1A19",
        "orange-50": "#FCF1E4",
        "orange-600": "#D43D00",
        "red-100": "#FFD4CA",
        "purple-700": "#3F0B81",

        // being used for gradient colors
        "red-intensity": "#FB957D",
        "purple-goal": "#D3B8FF",
        "blue-goal": "#A7F4F9",
        "blue-strategy": "#96C2FF",
        "green-strategy": "#AEE3B1",
        "emotion-yellow": "#F0F9A7",
        "library-pink": "#F7C7EB",
        "library-yellow": "#FFE49D",
        "thing-green": "#C3FFB1",
        "thing-yellow": "#F1FAA8",
        "green-light": "#A8F5FA",
        "blue-light": "#AFE4B2",
        "green-guide": "#A6F3F8",
        "purple-guide": "#D2B7FF",
      },
    },
  },
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        "scale-250": { transform: [{ scale: 2.5 }] },
        "origin-bottom": { transformOrigin: "bottom" },
        "border-px": { borderWidth: 1 },
        "border-none": {
          borderWidth: 0,
          borderBottomWidth: 0,
          bordertTopWidth: 0,
          borderLeftWidth: 0,
          borderRightWidth: 0,
        },
        "container-wrapper": "flex w-full bg-white",
        "resize-repeat": {
          resizeMode: `repeat`,
        },
        "size-full": "w-full h-full",
        "edge-match-parent": "top-0 left-0 right-0 bottom-0",
        centered: "justify-center items-center",
        "aspect-4-3": { aspectRatio: 4 / 3 },
        "aspect-3-4": { aspectRatio: 3 / 4 },
        "aspect-wide": { aspectRatio: 2.8 },
        "resize-contain": { resizeMode: "contain" },
        "text-vertical-top": { textAlignVertical: "top" },
        "text-vertical-bottom": { textAlignVertical: "bottom" },
        "text-vertical-center": { textAlignVertical: "center" },
        "text-vertical-auto": { textAlignVertical: "auto" },
        "text-3.5xl": { fontSize: 32, lineHeight: 40 },
      });
    }),
  ],
};
