import { Platform } from "react-native";
import {
    DefaultTheme as NavigationDefaultTheme,
    DarkTheme as NavigationDarkTheme,
} from '@react-navigation/native';
import { APP_COLORS } from "../colors";


export const CUSTOM_FONT_FAMILY = {
    "Avenir": Platform.select({
        ios: {
            Regular: 'AvenirNextCyr-Regular',
            Medium: 'AvenirNextCyr-Medium',
            Bold: 'AvenirNextCyr-Bold',
            Demi: 'AvenirNextCyr-Demi',
            Heavy: 'AvenirNextCyr-Heavy',
            Light: 'AvenirNextCyr-Light',
        },
        android: {
            Regular: 'AvenirNextCyr-Regular',
            Medium: 'AvenirNextCyr-Medium',
            Bold: 'AvenirNextCyr-Bold',
            Demi: 'AvenirNextCyr-Demi',
            Heavy: 'AvenirNextCyr-Heavy',
            Light: 'AvenirNextCyr-Light',
        }
    }),
    "Ginto": Platform.select({
        ios: {
            Black: 'ABCGintoNordBlackUnlicensedTrial-Black',
            BlackItalic: 'ABCGintoNordBlackUnlicensedTrial-BlackItalic',
            Bold: 'ABCGintoNordUnlicensedTrial-Bold',
            BoldItalic: 'ABCGintoNordUnlicensedTrial-BoldItalic',
            Hairline: 'ABCGintoNordHairlineUnlicensedTrial-Hairline',
            HairlineItalic: 'ABCGintoNordHairlineUnlicensedTrial-HairlineItalic',
            Light: 'ABCGintoNordLightUnlicensedTrial-Light',
            LightItalic: 'ABCGintoNordLightUnlicensedTrial-LightItalic',
            Medium: 'ABCGintoNordMediumUnlicensedTrial-Medium',
            Regular: 'ABCGintoNordUnlicensedTrial-Regular',
            RegularItalic: 'ABCGintoNordUnlicensedTrial-RegularItalic',
            Thin: 'ABCGintoNordThinUnlicensedTrial-Thin',
            ThinItalic: 'ABCGintoNordThinUnlicensedTrial-ThinItalic',
            Ultra: 'ABCGintoNordUltraUnlicensedTrial-Ultra',
            UltraItalic: 'ABCGintoNordUltraUnlicensedTrial-UltraItalic',
            Widths: 'ABCGintoNordWidthsUnlicensedTrial-Widths',
        },
        android: {
            Black: 'GintoNord-Black',
            BlackItalic: 'GintoNord-BlackItalic',
            Bold: 'GintoNord-Bold',
            BoldItalic: 'GintoNord-BoldItalic',
            Hairline: 'GintoNord-Hairline',
            HairlineItalic: 'GintoNord-HairlineItalic',
            Light: 'GintoNord-Light',
            LightItalic: 'GintoNord-LightItalic',
            Medium: 'GintoNord-Medium',
            Regular: 'GintoNord-Regular',
            RegularItalic: 'GintoNord-RegularItalic',
            Thin: 'GintoNord-Thin',
            ThinItalic: 'GintoNord-ThinItalic',
            Ultra: 'GintoNord-Ultra',
            UltraItalic: 'GintoNord-UltraItalic',
            Widths: 'GintoNordWidthsVariable',
        }
    }),
    "GintoNormal": Platform.select({
        ios: {
            Black: 'ABCGintoNormalBlackUnlicensedTrial-Black',
            BlackItalic: 'ABCGintoNormalBlackUnlicensedTrial-BlackItalic',
            Light: 'ABCGintoNormalLightUnlicensedTrial-Light',
            LightItalic: 'ABCGintoNormalLightUnlicensedTrial-LightItalic',
            Medium: 'ABCGintoNormalMediumUnlicensedTrial-Medium',
            MediumItalic: 'ABCGintoNormalMediumUnlicensedTrial-MediumItalic',
            Regular: 'ABCGintoNormalUnlicensedTrial-Regular',
            RegularItalic: 'ABCGintoNormalUnlicensedTrial-RegularItalic',
            Bold: 'ABCGintoNormalUnlicensedTrial-Bold',
            BoldItalic: 'ABCGintoNormalUnlicensedTrial-BoldItalic',
        },
        android: {
            Black: 'GintoNormal-Black',
            BlackItalic: 'GintoNormal-BlackItalic-Trial',
            Bold: 'GintoNormal-Bold-Trial',
            BoldItalic: 'GintoNormal-BoldItalic-Trial',
            Light: 'GintoNormal-Light-Trial',
            LightItalic: 'GintoNormal-LightItalic-Trial',
            Medium: 'GintoNormal-Medium-Trial',
            MediumItalic: 'GintoNormal-MediumItalic-Trial',
            Regular: 'GintoNormal-Regular-Trial',
            RegularItalic: 'GintoNormal-RegularItalic-Trial',
        },
    }),
    "GintoVariable": Platform.select({
        ios: {
            Regular: 'ABCGintoNordWidthsVariableUnlicensedTrial-Regular',
            RegularItalic: 'ABCGintoNordWidthsVariable-RegularItalic',
            Hairline: 'ABCGintoNordWidthsVariable-Hairline',
            HairlineItalic: 'ABCGintoNordWidthsVariable-HairlineItalic',
            Thin: 'ABCGintoNordWidthsVariable-Thin',
            ThinItalic: 'ABCGintoNordWidthsVariable-ThinItalic',
            Light: 'ABCGintoNordWidthsVariable-Light',
            LightItalic: 'ABCGintoNordWidthsVariable-LightItalic',
            Medium: 'ABCGintoNordWidthsVariable-Medium',
            MediumItalic: 'ABCGintoNordWidthsVariable-MediumItalic',
            Bold: 'ABCGintoNordWidthsVariable-Bold',
            BoldItalic: 'ABCGintoNordWidthsVariable-BoldItalic',
            Black: 'ABCGintoNordWidthsVariable-Black',
            BlackItalic: 'ABCGintoNordWidthsVariable-BlackItalic',
            Ultra: 'ABCGintoNordWidthsVariable-Ultra',
            UltraItalic: 'ABCGintoNordWidthsVariable-UltraItalic',
        },
        android: {
            Black: 'GintoNord-Black',
            BlackItalic: 'GintoNord-BlackItalic',
            Bold: 'GintoNord-Bold',
            BoldItalic: 'GintoNord-BoldItalic',
            Hairline: 'GintoNord-Hairline',
            HairlineItalic: 'GintoNord-HairlineItalic',
            Light: 'GintoNord-Light',
            LightItalic: 'GintoNord-LightItalic',
            Medium: 'GintoNord-Medium',
            Regular: 'GintoNord-Regular',
            RegularItalic: 'GintoNord-RegularItalic',
            Thin: 'GintoNord-Thin',
            ThinItalic: 'GintoNord-ThinItalic',
            Ultra: 'GintoNord-Ultra',
            UltraItalic: 'GintoNord-UltraItalic',
            Widths: 'GintoNordWidthsVariable',  
        },
    }),
    "GintoNormalVariable": Platform.select({
        ios: {
            Regular: 'ABCGintoNormalVariableUnlicensedTrial-Regular',
            RegularItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Regular-Italic',
            Hairline: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Hairline',
            HairlineItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Hairline-Italic',
            Thin: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Thin',
            ThinItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Thin-Italic',
            Light: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Light',
            LightItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Light-Italic',
            Medium: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Medium',
            MediumItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Medium-Italic',
            Bold: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Bold',
            BoldItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Bold-Italic',
            Black: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Black',
            BlackItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Black-Italic',
            Ultra: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Ultra',
            UltraItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Ultra-Italic',
        },
        android: {
            Regular: 'GintoNormalVariable-Regular',
            RegularItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Regular-Italic',
            Hairline: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Hairline',
            HairlineItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Hairline-Italic',
            Thin: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Thin',
            ThinItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Thin-Italic',
            Light: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Light',
            LightItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Light-Italic',
            Medium: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Medium',
            MediumItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Medium-Italic',
            Bold: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Bold',
            BoldItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Bold-Italic',
            Black: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Black',
            BlackItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Black-Italic',
            // Ultra: 'ABCGintoNormalVariableUnlicensedTrialRegular-Ultra',
            Ultra: 'GintoNormal-Black',
            UltraItalic: 'ABCGintoNormalVariableUnlicensedTrial-Regular_Ultra-Italic',
        },
    })

}


export const CUSTOM_DARK_THEME: any = {
    ...NavigationDarkTheme,
    colors: {
        ...NavigationDarkTheme.colors,
        background: APP_COLORS.BACKGROUND_DARK_NEW,
        card: APP_COLORS.BACKGROUND_DARK,
        text: APP_COLORS.TEXT_DARK,
        grayHeading: APP_COLORS.TEXT_GRAY_DARK,
        gray: APP_COLORS.BACKGROUND_GRAY_DARK,
        pollsFill: APP_COLORS.POLLS_BLUE_DARK,
        groupSettingIcon: APP_COLORS.GROUP_PERMISSION_BACKGROUND_DARK,
        groupSettingSwitch: APP_COLORS.GROUP_PERMISSION_SWITCH_DARK,
        groupSettingSwitchTrue: APP_COLORS.GROUP_PERMISSION_SWITCH_DARK,
        groupBalanceGray: APP_COLORS.BACKGROUND_GRAY_DARK,
        groupBalanceText: APP_COLORS.GROUP_BALANCE_TEXT_DARK,
        background_blue: APP_COLORS.BACKGROUND_BLUE_DARK,
        background_light_gray: APP_COLORS.BACKGROUND_LIGHT_GRAY_DARK,
    }
}


export const CUSTOM_LIGHT_THEME: any = {
    ...NavigationDefaultTheme,
    colors: {
        ...NavigationDefaultTheme.colors,
        background: APP_COLORS.BACKGROUND_LIGHT,
        card: APP_COLORS.BACKGROUND_LIGHT,
        text: APP_COLORS.TEXT_LIGHT,
        grayHeading: APP_COLORS.TEXT_GRAY_LIGHT,
        gray: APP_COLORS.BACKGROUND_GRAY_LIGHT,
        pollsFill: APP_COLORS.POLLS_BLUE_LIGHT,
        groupSettingIcon: APP_COLORS.GROUP_PERMISSION_BACKGROUND_LIGHT,
        groupSettingSwitch: APP_COLORS.GROUP_PERMISSION_SWITCH_LIGHT,
        groupBalanceGray: APP_COLORS.GROUP_BALANCE_GRAY_LIGHT,
        groupBalanceText: APP_COLORS.GROUP_BALANCE_TEXT_LIGHT,
        background_blue: APP_COLORS.BACKGROUND_LIGHT,
        background_light_gray: APP_COLORS.BACKGROUND_LIGHT,
    }
}